config/routes.rb
Rails.application.routes.draw do
  get 'posts/create'
  get 'posts/new'
  get 'pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :image_url, presence: true, format: URI::regexp(%w[http https])
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if params[:title].present?
      @posts = Post.where('title = ?', params[:title])
    else
      @posts = Post.all.order(created_at: :desc)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  def create
    @post = Post.create(title: params[:title], image_url: params[:image_url], content: params[:content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My blog!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  </head>

  <body class="no-sidebar is-preload">
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <script src="https://kit.fontawesome.com/1758aeb367.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
	<article id="main" class="special">
		<header>
			<br>
			<h2>DASHBOARD!</h2>
			<br>
			<h3>We will sensure the word "YOUR MOM" (in content section) because nobody can talk of my mommy.</h3>
			<p>All the posts are here! You can create a new post in "Create new post", obviously...</p>
		</header>
		<nav class="navbar navbar-light" id="search-nav">
			<p class="navbar-brand" id="search-ins">You can search a post using title!</p>
			<form class="form-inline" id="search-form">
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
		</nav>
		<div class="text-center">
			<% @posts.each do |post| %>
				<div>
					<hr>
					<h2><%= post.title %></h2>
					<br>
					<div class="image-container">
						<% if post.image_url.include?("http") %>
							<%= image_tag(post.image_url) %>
						<% else %>
							<%= image_tag("https://png.pngitem.com/pimgs/s/296-2968857_pixel-art-black-and-white-hd-png-download.png") %>
						<% end %>
					</div>
					<div class="content-container">
						<% if post.content.include? "YOUR MOM" %>
							<% post.content["YOUR MOM"] = "" %>
							<p><%= post.content %></p>
						<% else %>
							<p><%= post.content %></p>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
		<br>
    </article>
</div>

app/views/posts/create.html.erb
<div class="container">
    <hr>
    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@post.errors.count, "error") %>
                Prohibited this operation from being saved:
            </h2>
            <br>
            <ul>
                <%= @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
            <div class="text-center">
                <hr> 
                <h3>Try again <%= link_to 'HERE', posts_new_path %>.</h3>
            </div>
        </div>
    <% else %>
    <div class="text-center">
        <h1>Your post was uploated!</h1>
        <h2>Congrats, f***ng piece of s**t.</h2>
        <h3>Go to <%= link_to 'Dashboard', pages_index_path %>.</h3>
    </div>
    <% end %>
    <hr>
</div>

app/views/posts/new.html.erb
<div class="container">
	<article id="main" class="special">
        <br>
		<header>
			<h2>CREATE A NEW POST!</h2>
			<p>
				Here you can deposite your bullshit!
			</p>
		</header>
		<p class="text-center">
			This is your space. Feel free to post what you want, because this is a dead form.
		</p>
		<br>
    </article>
    <form id="create_posts" method="get" action="/posts/create">
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label>Title</label>
                <input type="text" name="title">
            </div>
            <div class="col-md-6 mb-3">
                <label>Image's URL</label>
                <input type="text" name="image_url">
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-12 mb-3">
                <label for="validationTextarea">Content</label>
                <textarea type="text" name="content"></textarea>
            </div>
        </div>
        <div class="text-center">
            <button class="btn btn-primary" type="submit">Submit form</button>
        </div>
    </form>
    <br>
</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<div id="footer">
	<div class="container">
				<!-- Copyright -->
					<div class="copyright">
						<ul class="menu">
							<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li><li>Form: <a href="https://github.com/PedroSebastiaan">PedroSebastiaan</a></li>
						</ul>
					</div>
		</div>
	</div>
</div>

app/views/shared/_header.html.erb
<!-- Header -->
<div id="header">
	<!-- Nav -->
		<nav id="nav" class="nav-content">
			<ul>
				<li><%= link_to 'Dashboard', pages_index_path %></li>
				<li><%= link_to 'Create new post', posts_new_path %></li>
			</ul>
		</nav>
</div>